PatientManager/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using PatientManager.Core.Application.Interfaces.Helpers;
using PatientManager.Core.Application.Interfaces.Services;
using PatientManager.Core.Application.ViewModels.Doctor;
using PatientManager.Middlewares;

namespace PatientManager.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorService _doctorService;
        private readonly IFileManager _fileManager;
        private readonly ValidateUserSession _validator;

        public DoctorController(IDoctorService doctorService, IFileManager fileManager, ValidateUserSession validator)
        {
            _doctorService = doctorService;
            _fileManager = fileManager;
            _validator = validator;
        }

        // GET: DoctorController
        public async Task<ActionResult> Index()
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View(await _doctorService.Get());
        }

        // GET: DoctorController/Create
        public ActionResult Create()
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View();
        }

        // POST: DoctorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(DoctorSaveViewModel vm)
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            try
            {
                vm.ImageUrl = await _fileManager.Save(vm.Image, "doctors");
                await _doctorService.Add(vm);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DoctorController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View(await _doctorService.GetById(id));
        }

        // POST: DoctorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, DoctorUpdateViewModel vm)
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            try
            {
                if(vm.Image != null)
                    vm.ImageUrl = await _fileManager.Update(vm.Image, "doctors", vm.ImageUrl);

                await _doctorService.Update(vm, id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DoctorController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View(await _doctorService.GetById(id));
        }

        // POST: DoctorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, DoctorUpdateViewModel vm)
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            try
            {
                vm = await _doctorService.GetById(id);

                if (vm.ImageUrl != null)
                    _fileManager.Delete("doctors", vm.ImageUrl);

                await _doctorService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PatientManager/Controllers/LabReportController.cs
using Microsoft.AspNetCore.Mvc;
using PatientManager.Core.Application.Interfaces.Services;
using PatientManager.Core.Application.ViewModels.LabReport;
using PatientManager.Middlewares;

namespace PatientManager.Controllers
{
    public class LabReportController : Controller
    {
        private readonly ILabReportService _labReportService;
        private readonly ValidateUserSession _validator;

        public LabReportController(ILabReportService labReportService, ValidateUserSession validator)
        {
            _labReportService = labReportService;
            _validator = validator;
        }

        public async Task<IActionResult> Index()
        {
            if (!_validator.IsAsistent())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View(await _labReportService.GetWithAll());
        }

        public async Task<ActionResult> Report(int id)
        {
            if (!_validator.IsAsistent())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View(await _labReportService.GetById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Report(int id, LabReportUpdateViewModel vm)
        {
            try
            {
                if (!_validator.IsAsistent())
                    return RedirectToRoute(new { controller = "Home", action = "Index" });

                await _labReportService.Update(vm, id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PatientManager/Controllers/LabTestController.cs
using Microsoft.AspNetCore.Mvc;
using PatientManager.Core.Application.Interfaces.Services;
using PatientManager.Core.Application.ViewModels.LabTest;
using PatientManager.Middlewares;

namespace PatientManager.Controllers
{
    public class LabTestController : Controller
    {
        private readonly ILabTestService _labTestService;
        private readonly ValidateUserSession _validator;


        public LabTestController(ILabTestService labTestService, ValidateUserSession validator)
        {
            _labTestService = labTestService;
            _validator = validator;
        }

        // GET: LabTestController
        public async Task<ActionResult> Index()
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View(await _labTestService.Get());
        }

        // GET: LabTestController/Create
        public ActionResult Create()
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View();
        }

        // POST: LabTestController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LabTestSaveViewModel vm)
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            try
            {
                await _labTestService.Add(vm);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LabTestController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View(await _labTestService.GetById(id));
        }

        // POST: LabTestController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, LabTestUpdateViewModel vm)
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            try
            {
                await _labTestService.Update(vm, id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LabTestController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View(await _labTestService.GetById(id));
        }

        // POST: LabTestController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, LabTestUpdateViewModel vm)
        {
            if (!_validator.IsAdmin())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            try
            {
                await _labTestService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PatientManager/Controllers/PatientController.cs
using Microsoft.AspNetCore.Mvc;
using PatientManager.Core.Application.Interfaces.Helpers;
using PatientManager.Core.Application.Interfaces.Services;
using PatientManager.Core.Application.ViewModels.Patient;
using PatientManager.Middlewares;

namespace PatientManager.Controllers
{
    public class PatientController : Controller
    {
        private readonly IPatientService _patientService;
        private readonly IFileManager _fileManager;
        private readonly ValidateUserSession _validator;

        public PatientController(IPatientService patientService, IFileManager fileManager, ValidateUserSession validator)
        {
            _patientService = patientService;
            _fileManager = fileManager;
            _validator = validator;
        }

        // GET: PatientController
        public async Task<ActionResult> Index()
        {
            if (!_validator.IsAsistent())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View(await _patientService.Get());
        }

        // GET: PatientController/Create
        public ActionResult Create()
        {
            if (!_validator.IsAsistent())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View();
        }

        // POST: PatientController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PatientSaveViewModel vm)
        {
            if (!_validator.IsAsistent())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            try
            {
                vm.ImageUrl = await _fileManager.Save(vm.Image, "patients");
                await _patientService.Add(vm);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PatientController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            if (!_validator.IsAsistent())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View(await _patientService.GetById(id));
        }

        // POST: PatientController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, PatientUpdateViewModel vm)
        {
            if (!_validator.IsAsistent())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            try
            {
                if (vm.Image != null)
                    vm.ImageUrl = await _fileManager.Update(vm.Image, "patients", vm.ImageUrl);

                await _patientService.Update(vm, id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PatientController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            if (!_validator.IsAsistent())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            return View(await _patientService.GetById(id));
        }

        // POST: PatientController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, PatientUpdateViewModel vm)
        {
            if (!_validator.IsAsistent())
                return RedirectToRoute(new { controller = "Home", action = "Index" });

            try
            {
                vm = await _patientService.GetById(id);

                if (vm.ImageUrl != null)
                    _fileManager.Delete("patients", vm.ImageUrl);

                await _patientService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PatientManager/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using PatientManager.Core.Application.Helpers;
@using PatientManager.Core.Application.ViewModels.User;

@inject IHttpContextAccessor httpContext;

@{
    UserViewModel User = httpContext.HttpContext.Session.Get<UserViewModel>("user");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PatientManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PatientManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="@(User != null ? "Home" : "User")" asp-action="@(User != null ? "Index" : "Login")">PatientManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(User != null)
                        {
                            @if(User.UserType == "Administrador")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Usuarios</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Medicos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="LabTest" asp-action="Index">Pruebas de Laboratorio</a>
                                </li>
                            }
                            @if(User.UserType == "Asistente")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="Index">Pacientes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="Index">Citas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="LabReport" asp-action="Index">Resultados</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Cerrar Sesión</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PatientManager
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>